### ISSUE TITLE
How to update the collection correctly?

### ISSUE THREAD

**Issue by highkay** [center-for-threat-informed-defense/attack-workbench-collection-manager#46]
I fork the stix data repo and translate it. then I upload to the collection manager via the web ui. Later I fix some translate typo issues and upload them again, the upload failed, then I change the collection file uuid field and success. But I think it is not the right way to update a collection, maybe the same uuid and different version field should be the right way. 

btw. I found the api to remove a collection not work, is it a feature not implemented yet or a bug?

**Comment by ElJocko** [comment]
Manual editing of collections is not currently supported.

The DELETE /api/collections/:stixId endpoint is implemented. Please feel free to reopen this issue if you're able to provide more context for the problem you've encountered.
